AWSTemplateFormatVersion: '2010-09-09'
Description: Cognito Stack
Parameters:
  Stage:
    Type: String
    Default: dev
  Domain:
    Type: String
    Description: The domain name auth client
    Default: auth.ethiopia-covid19.com
  ResourceIdentifier:
    Type: String
    Description: The domain name auth client
    Default: https://api.ethiopia-covid19.com/covid-gateway/resource
  pCertificateArn:
    Description: Certificate Arn for the domain
    Type: String
    Default: "arn:aws:acm:us-east-2:689384711846:certificate/fefdfc46-d450-46d4-be46-2c34c100c65e"
Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${Stage}-user-pool'

  ResourceServer:
    Type: AWS::Cognito::UserPoolResourceServer
    Properties:
      UserPoolId: !Ref UserPool
      Identifier: !Ref ResourceIdentifier
      Name: Resource
      Scopes:
        - ScopeName: read
          ScopeDescription: read
        - ScopeName: update
          ScopeDescription: update
        - ScopeName: create
          ScopeDescription: create
        - ScopeName: delete
          ScopeDescription: delete
        - ScopeName: list
          ScopeDescription: list
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: OAuthClient
      GenerateSecret: True
      AllowedOAuthScopes:
        - !Sub ${ResourceIdentifier}/read
        - !Sub ${ResourceIdentifier}/update
        - !Sub ${ResourceIdentifier}/create
        - !Sub ${ResourceIdentifier}/delete
        - !Sub ${ResourceIdentifier}/list
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthFlows:
        - client_credentials

  PoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref Domain
      UserPoolId: !Ref UserPool
    #  CustomDomainConfig: 
    #    CertificateArn: !Ref pCertificateArn

Outputs:
  OauthTokenUrl:
    Value:
      !Sub 'https://${Domain}.auth.${AWS::Region}.amazoncognito.com'
    Export:
      Name: !Sub '${Stage}-oauth-token-url'
  ProviderURL:
    Value:
      !GetAtt UserPool.ProviderURL
    Export:
      Name: !Sub '${Stage}-provider-url'